In [2]:
## pandas series , pandas data frame 
## a dataframe is basicllly a two dimensional labelled data structure with columns of patentially 
## different types , similar to excel speadsheet
# pandas libaries function h jo data ko analysis and manipulate karta h

In [3]:
import pandas as pd

In [4]:
data = {
    'name' : ['ajay' , 'Bobby', 'sunny'],
    'age' : [24,56,67],
    'city' : ['paris', 'pune','punjab']
}
print(data)

{'name': ['ajay', 'Bobby', 'sunny'], 'age': [24, 56, 67], 'city': ['paris', 'pune', 'punjab']}

In [5]:
df = pd.DataFrame(data)    
print(df)  ## ya df only likh sakte h

    name  age    city
0   ajay   24   paris
1  Bobby   56    pune
2  sunny   67  punjab

In [6]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [7]:
print(df.columns)  ## columns names

Index(['name', 'age', 'city'], dtype='object')

In [8]:
print(df.shape)  ## rows and columns

(3, 3)

In [9]:
print(df.dtypes) ## data types for each individual column

name    object
age      int64
city    object
dtype: object

In [10]:
print(df.head(2)) # any number of records from the 1st

    name  age   city
0   ajay   24  paris
1  Bobby   56   pune

In [11]:
df.tail(2)  # any number of records from the last 
## as well write with print

    name  age    city
1  Bobby   56    pune
2  sunny   67  punjab

In [12]:
#3 how to take data in pandas datafame from your system

## D:/---- Folder(data) -- titles.csv
title_data = pd.read_csv("D:/pandas/titles.csv")   ## path / file
print(title_data.head(5))

                     title  year
0           The Rising Son  1990
1  The Thousand Plane Raid  1969
2         Crucea de piatra  1993
3                  Country  2000
4               Gaiking II  2011

In [13]:
print(title_data.head())

                     title  year
0           The Rising Son  1990
1  The Thousand Plane Raid  1969
2         Crucea de piatra  1993
3                  Country  2000
4               Gaiking II  2011

In [14]:
## can you do the above dta frame operaations, tell me how many data do we have 
print(title_data.shape)  ## num of rows and columns

(230621, 2)

In [15]:
## describe all about the statistic like mean , std, min count 25% etc 
print(title_data.describe())  ## describe data

                year
count  230621.000000
mean     1985.695097
std        29.371587
min      1894.000000
25%      1966.000000
50%      1995.000000
75%      2011.000000
max      2026.000000

In [16]:
print(title_data.info())  ## information f the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230621 entries, 0 to 230620
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   title   230620 non-null  object
 1   year    230621 non-null  int64
dtypes: int64(1), object(1)
memory usage: 3.5+ MB
None

In [17]:
data_file = pd.read_csv("D:/pandas/Employee_Building.csv")
print(data_file.describe())

       Years_employed
count       15.000000
mean         4.333333
std          2.919556
min          0.000000
25%          2.000000
50%          4.000000
75%          6.500000
max          9.000000

In [18]:
print(data_file.shape)

(15, 4)

In [19]:
print(data_file.head(23))  ## 14 only 15 rows here

        Role        Name Building  Years_employed
0   Engineer    Becky A.       1e               4
1   Engineer      Dan B.       1e               2
2   Engineer   Sharon F.       1e               6
3   Engineer      Dan M.       1e               4
4   Engineer   Malcom S.       1e               1
5     Artist    Tylar S.       2w               2
6     Artist  Sherman D.       2w               8
7     Artist    Jakob J.       2w               6
8     Artist   Lillia A.       2w               7
9     Artist  Brandon J.       2w               7
10   Manager    Scott K.       1e               9
11   Manager  Shirlee M.       1e               3
12   Manager    Daria O.       2w               6
13  Engineer    Yancy I.      NaN               0
14    Artist   Oliver P.      NaN               0

In [20]:
print(data_file.dtypes)
print(data_file.info)

Role              object
Name              object
Building          object
Years_employed     int64
dtype: object
<bound method DataFrame.info of         Role        Name Building  Years_employed
0   Engineer    Becky A.       1e               4
1   Engineer      Dan B.       1e               2
2   Engineer   Sharon F.       1e               6
3   Engineer      Dan M.       1e               4
4   Engineer   Malcom S.       1e               1
5     Artist    Tylar S.       2w               2
6     Artist  Sherman D.       2w               8
7     Artist    Jakob J.       2w               6
8     Artist   Lillia A.       2w               7
9     Artist  Brandon J.       2w               7
10   Manager    Scott K.       1e               9
11   Manager  Shirlee M.       1e               3
12   Manager    Daria O.       2w               6
13  Engineer    Yancy I.      NaN               0
14    Artist   Oliver P.      NaN               0>

In [21]:
## ye pure data me decimal hatane ka kaam karega 
pd.set_option('display.float_format','{:.0f}'.format)

In [22]:
df['salary'] = [10000, 1200, 1400]  # add column 
df

    name  age    city  salary
0   ajay   24   paris   10000
1  Bobby   56    pune    1200
2  sunny   67  punjab    1400

In [24]:
data_file

        Role        Name Building  Years_employed
0   Engineer    Becky A.       1e               4
1   Engineer      Dan B.       1e               2
2   Engineer   Sharon F.       1e               6
3   Engineer      Dan M.       1e               4
4   Engineer   Malcom S.       1e               1
5     Artist    Tylar S.       2w               2
6     Artist  Sherman D.       2w               8
7     Artist    Jakob J.       2w               6
8     Artist   Lillia A.       2w               7
9     Artist  Brandon J.       2w               7
10   Manager    Scott K.       1e               9
11   Manager  Shirlee M.       1e               3
12   Manager    Daria O.       2w               6
13  Engineer    Yancy I.      NaN               0
14    Artist   Oliver P.      NaN               0

In [27]:
data_file.isnull().sum()

Role              0
Name              0
Building          2
Years_employed    0
dtype: int64